workflow:
  name: SQLGenerator-CI

variables:
  JDK_MAVEN: base-jdk-8-maven:v381
  PKG_NAME: SQLGeneratorCore.jar

default:
  image: registry.cn-beijing.aliyuncs.com/suanchang/$JDK_MAVEN

stages:
  - maven-deploy

maven-deploy:
  stage: maven-deploy
  script:
    - mvn clean install org.apache.maven.plugins:maven-deploy-plugin:2.8:deploy -DskipTests
    - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" 
      --upload-file SG-Core/target/${PKG_NAME}
      "${CI_API_V4_URL}/api/v4/projects/${CI_PROJECT_ID}/packages/generic/SQLGenerator/snapshot/${PKG_NAME}?select=package_file"'
  rules:
    - if: '$CI_PIPELINE_SOURCE != "pipeline"'


