workflow:
  name: SQLGenerator-CI

variables:
  JDK_MAVEN: base-jdk-8-maven:v381
  SNAPSHOT: 1.0-SNAPSHOT
  RAW_PKG_NAME: SQLGenerator-Core-1.0-SNAPSHOT.jar
  PKG_NAME: SQLGeneratorCore.jar
  WITH_DEPENDENCIES: WITH-DEPENDENCIES
  API_URL: projects/238/packages/maven/org/lee/SQLGenerator-Core
  API_PARAM: status=default&select=package_file
  TARGET_FILE_PATH: core/target

default:
  image: registry.cn-beijing.aliyuncs.com/suanchang/$JDK_MAVEN

stages:
  - maven-deploy

maven-deploy:
  stage: maven-deploy
  script:
    - mvn clean install org.apache.maven.plugins:maven-deploy-plugin:2.8:deploy -DskipTests
    - echo ${CI_API_V4_URL}/${API_URL}/${SNAPSHOT}/${RAW_PKG_NAME}
    - echo ${CI_API_V4_URL}/${API_URL}/${SNAPSHOT}-${WITH_DEPENDENCIES}/${PKG_NAME}
    - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" 
    --upload-file ${TARGET_FILE_PATH}/${RAW_PKG_NAME}
    "${CI_API_V4_URL}/${API_URL}/${SNAPSHOT}/${RAW_PKG_NAME}?${API_PARAM}"'
    - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" 
    --upload-file ${TARGET_FILE_PATH}/${PKG_NAME} 
    "${CI_API_V4_URL}/${API_URL}/${SNAPSHOT}-${WITH_DEPENDENCIES}/${PKG_NAME}?${API_PARAM}"'
  rules:
    - if: '$CI_PIPELINE_SOURCE != "pipeline"'


