package org.lee.common.config;

public enum Conf {
    SYNTAX_TYPE,
    MAX_SUBQUERY_RECURSION_DEPTH,
    MAX_EXPRESSION_RECURSION_DEPTH,
    MAX_SETOP_RECURSION_DEPTH,
    CONVERT_TO_PARTITION_PROB,
    CONVERT_TO_PIVOTED_PROB,
    USING_VALUES_IN_FROM_PROBABILITY,
    USING_SUBQUERY_IN_FROM_PROBABILITY,
    MAX_FROM_CLAUSE_RTE_JOIN_NUM,
    MAX_RTE_JOIN_ENTRY_NUM,
    USING_MATERIALIZED_CTE_PROB,
    MAX_CONDITION_COMBINE_DEPTH,
    CONDITION_COMBINE_PROB,
    CONDITION_COMBINE_GROWTH_PROB,
    WITH_CTE_PROBABILITY,
    WHERE_CLAUSE_FUZZ_PROBABILITY,
    LIMIT_OFFSET_CLAUSE_FUZZ_PROBABILITY,
    LIMIT_OFFSET_WITH_OFFSET_PROBABILITY,
    GROUP_BY_CLAUSE_FUZZ_PROBABILITY,
    HAVING_CLAUSE_FUZZ_PROBABILITY,
    SORT_BY_CLAUSE_FUZZ_PROBABILITY,
    MAX_SELECT_WHERE_FILTER_NUM,
    MAX_SELECT_JOIN_FILTER_NUM,
    SELECT_JOIN_FILTER_APPEND_PROBABILITY,
    SELECT_WHERE_FILTER_APPEND_PROBABILITY,
    EXPRESSION_APPEND_AGGREGATION_PROB,
    EXPRESSION_RECURSION_PROBABILITY,
    VALUES_STATEMENT_AS_SUBQUERY_PROBABILITY,
    SETOP_STATEMENT_AS_SUBQUERY_PROBABILITY,
    PURE_SELECT_AS_SUBQUERY_PROBABILITY,
    ;
    // implement how to check value
    Conf(){

    }
}
